# Generated by Django 4.0.3 on 2022-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='vac',
            field=models.BigIntegerField(),
        ),
    ]
