# Generated by Django 4.0.3 on 2022-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_vacancies_vac'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='id1',
            field=models.BigIntegerField(default=1),
        ),
    ]
