# Generated by Django 4.0.3 on 2022-11-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_vacancies_id1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vacancies',
            new_name='vacancies1',
        ),
    ]
