# Generated by Django 4.0.3 on 2022-11-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_vacancies_vacancies1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
