# Generated by Django 4.0.3 on 2022-11-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_attendance_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='Image1',
        ),
    ]
