# Generated by Django 4.0.3 on 2022-11-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_books_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='b1',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='b2',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='b3',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
