# Generated by Django 4.0.3 on 2022-11-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_student_b1_alter_student_b2_alter_student_b3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='b1',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='b2',
            field=models.CharField(default='NA', max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='b3',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
