# Generated by Django 4.0.3 on 2022-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_student_b1_alter_student_b2_alter_student_b3'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.CharField(default='Nov', max_length=50),
        ),
    ]
