# Generated by Django 4.0.3 on 2022-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_attendance_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.CharField(default='November', max_length=50),
        ),
    ]
