# Generated by Django 4.0.3 on 2022-11-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_attendance_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('paper', models.FileField(upload_to='')),
            ],
        ),
    ]
