# Generated by Django 4.0.3 on 2022-11-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_papers_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='papers1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept1', models.CharField(max_length=100)),
                ('paper1', models.URLField()),
            ],
        ),
    ]
